
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Experiment4(

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



wire [31:0] reg_out, PC;
hexto7seg hex_0 (.hexn(HEX0),.hex(reg_out[3:0]));
hexto7seg hex_1 (.hexn(HEX1),.hex(reg_out[7:4]));
hexto7seg hex_2 (.hexn(HEX2),.hex(reg_out[11:8]));
hexto7seg hex_3 (.hexn(HEX3),.hex(reg_out[15:12]));

hexto7seg hex_4 (.hexn(HEX4),.hex(PC[3:0]));
hexto7seg hex_5 (.hexn(HEX5),.hex(PC[7:4]));


Pipeline_Computer my_computer(
    .clk(~KEY[0]),
    .reset(~KEY[1]),
    .Debug_Source_select(SW[3:0]),
    .fetchPC(PC),    
	 .Debug_out(reg_out),
    .StallF(LEDR[3]),
	 .StallD(LEDR[2]),
	 .FlushD(LEDR[1]),
	 .FlushE(LEDR[0])
);

endmodule
